spring.application.name=InventoryMgtSystem
server.port=5050


# POSTGRESQL CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=3678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Debug Logging for Spring Security
logging.level.org.springframework.security=DEBUG

#THE MAXIMUM SIGN OF IMAGE THAT CAN BE UPLOADED
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
secreteJwtString=phegondev123456789phegondev123456789

